version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

volumes:
  data: {}